name: torri_cantine_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number fgit config --global user.name "Sidney Jones"or your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.7.3

environment:
  sdk: '>=2.18.6 <3.0.0'
#  sdk: '>=3.4.0 <4.0.0'

isar_version: &isar_version 3.1.0 # define the version to be used


dependencies:
  flutter:
    sdk: flutter


  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  cupertino_icons: ^1.0.2
  flutter_bloc: 7.0.0
  easy_localization: ^3.0.1
  freezed: 2.2.0
  dio: ^4.0.6
  http_services: ^2.1.1
  flutter_svg: ^2.0.4
  configurable_expansion_tile_null_safety: ^3.2.0
  image_picker: ^0.8.7
  google_fonts: ^4.0.3
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.0.1
  #youtube_player_iframe: ^3.1.0
  #youtube_player_iframe: ^5.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.3
  badges: ^3.1.1
  url_launcher: ^6.1.11
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^4.3.0
  uuid: ^3.0.7
  external_app_launcher: ^4.0.0
  #flutter_paypal: ^0.0.7
  flutter_paypal: ^0.2.0
  infinite_scroll_pagination: ^3.2.0
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0-beta.2
  flutter_stripe: ^9.4.0
  flutter_facebook_auth: ^6.0.4
  freezed_annotation: ^2.4.1
  flutter_meta_sdk: ^1.0.2
  html_unescape: ^2.0.0
  device_info_plus: ^10.1.0
  path_provider: ^2.1.4
  flutter_cache_manager: ^3.3.1
  shared_preferences: ^2.3.2

dependency_overrides:
  stripe_android: "9.5.0+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  build_runner: ^2.0.1
  json_serializable: ^6.5.4
  hive_generator: ^2.0.0
  json_annotation: ^4.9.0
  #analyzer: ^6.8.0
  isar_generator: *isar_version
  build_runner: any

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app-icon.png"
  image_path_ios: "assets/app-icon.png"
  adaptive_icon_background: "#922a24"
  adaptive_icon_foreground: "assets/app-icon.png"
  remove_alpha_ios: false


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#flutter pub run flutter_launcher_icons
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages