// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBeomPUSoTS7dSgImcQ_05YUrXWg5s4SE',
    appId: '1:683059644780:web:b6b9d1e23538413056cb49',
    messagingSenderId: '683059644780',
    projectId: 'torricantinestore',
    authDomain: 'torricantinestore.firebaseapp.com',
    storageBucket: 'torricantinestore.firebasestorage.app',
    measurementId: 'G-KYVSLZSFL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOBvcMOccdxMdpF80dtk-NTwUM0CIp85I',
    appId: '1:683059644780:android:60b2ddddb8c7cd4456cb49',
    messagingSenderId: '683059644780',
    projectId: 'torricantinestore',
    storageBucket: 'torricantinestore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-bK3WNav1WzIPK3vqZ1_lVQsOQN5hZbI',
    appId: '1:683059644780:ios:2d6996dbca63b4fd56cb49',
    messagingSenderId: '683059644780',
    projectId: 'torricantinestore',
    storageBucket: 'torricantinestore.firebasestorage.app',
    androidClientId: '683059644780-0o5nb8kbr40oj0n3u74a1m9romlijlvb.apps.googleusercontent.com',
    iosClientId: '683059644780-lv5jd91h62tgvqg41m7btml9h2dkapfv.apps.googleusercontent.com',
    iosBundleId: 'com.torricantineapp.torristore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-bK3WNav1WzIPK3vqZ1_lVQsOQN5hZbI',
    appId: '1:683059644780:ios:883ffb835bdef32156cb49',
    messagingSenderId: '683059644780',
    projectId: 'torricantinestore',
    storageBucket: 'torricantinestore.firebasestorage.app',
    androidClientId: '683059644780-0o5nb8kbr40oj0n3u74a1m9romlijlvb.apps.googleusercontent.com',
    iosClientId: '683059644780-l3qu4btmfqvaienlkjqlp7bk4265ogr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.torriCantineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPbZQUgFE14QkX6DCUr7-2R1rKmE8C8gU',
    appId: '1:683059644780:web:75b9e3d025cda65b56cb49',
    messagingSenderId: '683059644780',
    projectId: 'torricantinestore',
    authDomain: 'torricantinestore.firebaseapp.com',
    storageBucket: 'torricantinestore.firebasestorage.app',
    measurementId: 'G-WJWBXNRJQ8',
  );

}