// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBeomPUSoTS7dSgImcQ_05YUrXWg5s4SE',
    appId: '1:683059644780:web:b6b9d1e23538413056cb49',
    messagingSenderId: '683059644780',
    projectId: 'torricantinestore',
    authDomain: 'torricantinestore.firebaseapp.com',
    storageBucket: 'torricantinestore.appspot.com',
    measurementId: 'G-KYVSLZSFL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOBvcMOccdxMdpF80dtk-NTwUM0CIp85I',
    appId: '1:683059644780:android:08b3b6e3c2dcc74656cb49',
    messagingSenderId: '683059644780',
    projectId: 'torricantinestore',
    storageBucket: 'torricantinestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-bK3WNav1WzIPK3vqZ1_lVQsOQN5hZbI',
    appId: '1:683059644780:ios:c7f1035c2ed7ae2556cb49',
    messagingSenderId: '683059644780',
    projectId: 'torricantinestore',
    storageBucket: 'torricantinestore.appspot.com',
    androidClientId: '683059644780-tjrqhnqie2rsn7bnfj57d2u5121i3d15.apps.googleusercontent.com',
    iosClientId: '683059644780-l3qu4btmfqvaienlkjqlp7bk4265ogr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.torriCantineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-bK3WNav1WzIPK3vqZ1_lVQsOQN5hZbI',
    appId: '1:683059644780:ios:c7f1035c2ed7ae2556cb49',
    messagingSenderId: '683059644780',
    projectId: 'torricantinestore',
    storageBucket: 'torricantinestore.appspot.com',
    androidClientId: '683059644780-tjrqhnqie2rsn7bnfj57d2u5121i3d15.apps.googleusercontent.com',
    iosClientId: '683059644780-l3qu4btmfqvaienlkjqlp7bk4265ogr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.torriCantineApp',
  );
}
